# Generated by Django 5.2 on 2025-05-08 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_aid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='needs_resources',
            field=models.BooleanField(default=False),
        ),
    ]
