# Generated by Django 5.2 on 2025-05-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_aid', '0002_incidentreport_needs_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='incident_photos/'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='incident_photos/'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='incident_photos/'),
        ),
    ]
