# Generated by Django 5.2 on 2025-05-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_aid', '0004_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='denial_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('denied', 'Denied')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='notification_type',
            field=models.CharField(choices=[('incident_verified', 'Incident Verified'), ('incident_denied', 'Incident Denied'), ('resource_approved', 'Resource Request Approved'), ('resource_fulfilled', 'Resource Request Fulfilled')], max_length=50),
        ),
    ]
