# Generated by Django 4.2.17 on 2025-05-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_aid', '0006_barangay_municipality_alter_incidentreport_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='incident_datetime',
            field=models.DateTimeField(blank=True, help_text='When the incident actually occurred', null=True),
        ),
    ]
