# Generated by Django 4.2.17 on 2025-05-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_aid', '0008_disasteralert'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='other_disaster_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
