# Generated by Django 4.2.17 on 2025-05-08 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_aid', '0009_incidentreport_other_disaster_type'),
        ('disaster_aid', 'add_others_disaster_type'),
    ]

    operations = [
    ]
