# Generated by Django 4.2.17 on 2025-05-08 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_aid', '0010_add_others_disaster_type'),
        ('disaster_aid', '0010_merge_20250508_1645'),
    ]

    operations = [
    ]
