# Generated by Django 4.2.17 on 2025-05-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_aid', '0011_merge_20250508_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentdistribution',
            name='recipient',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incidentdistribution',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('distributed', 'Distributed')], default='pending', max_length=20),
        ),
    ]
