# Generated by Django 4.2.17 on 2025-05-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_aid', '0012_incidentdistribution_recipient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidentdistribution',
            old_name='recipient',
            new_name='distributed_by',
        ),
        migrations.AddField(
            model_name='incidentdistribution',
            name='distribution_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentdistribution',
            name='distribution_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentdistribution',
            name='recipient_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incidentdistribution',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incidentdistribution',
            name='recipient_organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
