# Generated by Django 4.2.17 on 2025-05-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_aid', '0013_rename_recipient_incidentdistribution_distributed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentdistribution',
            name='beneficiary_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
