# Generated by Django 4.2.17 on 2025-05-08 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_aid', '0014_incidentdistribution_beneficiary_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporterprofile',
            name='barangay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='disaster_aid.barangay'),
        ),
    ]
