# Generated by Django 4.2.17 on 2025-05-08 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disaster_aid', '0015_reporterprofile_barangay'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvacuationCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(help_text='Detailed address of the evacuation center')),
                ('capacity', models.PositiveIntegerField(help_text='Maximum number of people the center can accommodate')),
                ('current_occupancy', models.PositiveIntegerField(default=0, help_text='Current number of people in the center')),
                ('status', models.CharField(choices=[('active', 'Active'), ('standby', 'Standby'), ('closed', 'Closed')], default='standby', max_length=20)),
                ('contact_info', models.CharField(blank=True, help_text='Contact information for the evacuation center', max_length=255, null=True)),
                ('facilities', models.TextField(blank=True, help_text='Available facilities (e.g., toilets, kitchen, medical area)', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the evacuation center', null=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evacuation_centers', to='disaster_aid.barangay')),
                ('manager', models.ForeignKey(blank=True, help_text='Barangay captain or designated manager of this evacuation center', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='reporterprofile',
            name='is_barangay_captain',
            field=models.BooleanField(default=False, help_text='Designates whether this user is a barangay captain'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='notification_type',
            field=models.CharField(choices=[('incident_verified', 'Incident Verified'), ('incident_denied', 'Incident Denied'), ('resource_approved', 'Resource Request Approved'), ('resource_fulfilled', 'Resource Request Fulfilled'), ('evacuation_activated', 'Evacuation Center Activated'), ('evacuation_update', 'Evacuation Center Update')], max_length=50),
        ),
        migrations.CreateModel(
            name='Evacuee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('head_of_family', models.BooleanField(default=False)),
                ('family_name', models.CharField(blank=True, help_text='Family name for grouping related evacuees', max_length=255, null=True)),
                ('special_needs', models.TextField(blank=True, help_text='Any special needs or medical conditions', null=True)),
                ('date_admitted', models.DateTimeField(auto_now_add=True)),
                ('date_departed', models.DateTimeField(blank=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('evacuation_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evacuees', to='disaster_aid.evacuationcenter')),
            ],
        ),
        migrations.AddField(
            model_name='usernotification',
            name='evacuation_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disaster_aid.evacuationcenter'),
        ),
    ]
