# Generated by Django 4.2.17 on 2025-05-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_aid', '0016_evacuationcenter_reporterprofile_is_barangay_captain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporterprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
